import { useState } from "react";
import { useIsMobile } from "@/hooks/use-mobile";
import Sidebar from "@/components/dashboard/sidebar";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Menu, Leaf, Download, TrendingUp, Globe, Factory } from "lucide-react";
import { environmentalData } from "@/lib/data";
import { useToast } from "@/hooks/use-toast";

export default function EnvironmentalReports() {
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);
  const isMobile = useIsMobile();
  const { toast } = useToast();

  const handleDownloadReport = () => {
    const reportData = `
Kitar360 Smart Waste Management - Provided by HijauNet
Generated: ${new Date().toLocaleDateString()}

=== SUMMARY ===
Carbon Saved: ${environmentalData.carbonSaved} tons CO2
Landfill Diverted: ${environmentalData.landfillDiverted} kg
Recycling Efficiency: ${environmentalData.recyclingEfficiency}%

=== MONTHLY TRENDS ===
${environmentalData.monthlyTrends
  .map(
    (month) =>
      `${month.month}: ${month.recycled}kg recycled of ${month.total}kg total (${Math.round((month.recycled / month.total) * 100)}%)`,
  )
  .join("\n")}

=== ENVIRONMENTAL BENEFITS ===
• Reduced greenhouse gas emissions by ${environmentalData.carbonSaved} tons
• Diverted ${environmentalData.landfillDiverted} kg of waste from landfills
• Achieved ${environmentalData.recyclingEfficiency}% recycling efficiency
• Supported circular economy principles in Brunei

Report generated by Kitar360 Smart Waste Management System
    `;

    const blob = new Blob([reportData], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `environmental-report-${new Date().toISOString().split("T")[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast({
      title: "Report Downloaded",
      description:
        "Environmental impact report has been downloaded successfully",
    });
  };

  const calculateProgress = (current: number, target: number) => {
    return Math.min((current / target) * 100, 100);
  };

  return (
    <div className="flex min-h-screen bg-gray-50">
      {/* Mobile Menu Toggle */}
      {isMobile && (
        <div className="fixed top-4 left-4 z-50 lg:hidden">
          <Button
            variant="outline"
            size="icon"
            onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
            className="bg-white shadow-md"
          >
            <Menu className="h-4 w-4" />
          </Button>
        </div>
      )}

      {/* Sidebar */}
      <Sidebar
        isOpen={isMobileMenuOpen}
        onClose={() => setIsMobileMenuOpen(false)}
        isMobile={isMobile}
      />

      {/* Mobile Overlay */}
      {isMobile && isMobileMenuOpen && (
        <div
          className="fixed inset-0 bg-black bg-opacity-50 z-30 lg:hidden"
          onClick={() => setIsMobileMenuOpen(false)}
        />
      )}

      {/* Main Content */}
      <div className="flex-1 lg:ml-0">
        {/* Header */}
        <header className="bg-white shadow-sm border-b border-gray-200">
          <div className="px-4 sm:px-6 lg:px-8">
            <div className="flex items-center justify-between h-16">
              <div className="flex items-center">
                <div className="ml-12 lg:ml-0">
                  <h1 className="text-lg sm:text-xl lg:text-2xl font-bold text-gray-900">
                    Environmental Reports
                  </h1>
                  <p className="text-sm text-gray-600 mt-1 hidden sm:block">
                    Track environmental impact and sustainability metrics
                  </p>
                  <p className="text-sm text-gray-600 mt-1 sm:hidden">
                    Environmental impact
                  </p>
                </div>
              </div>
              <div className="flex items-center space-x-4">
                <Button
                  onClick={handleDownloadReport}
                  className="green-primary hover:bg-green-600 text-white"
                >
                  <Download className="w-4 h-4 mr-2" />
                  Download Report
                </Button>
              </div>
            </div>
          </div>
        </header>

        <main className="px-4 sm:px-6 lg:px-8 py-8">
          {/* Impact Summary */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
            <Card>
              <CardContent className="p-6">
                <div className="flex items-center">
                  <div className="p-3 green-light rounded-lg">
                    <Leaf className="w-6 h-6 text-green-primary" />
                  </div>
                  <div className="ml-4">
                    <p className="text-sm font-medium text-gray-600">
                      Carbon Saved
                    </p>
                    <p className="text-2xl font-bold text-gray-900">
                      {environmentalData.carbonSaved} tons CO2
                    </p>
                    <p className="text-xs text-green-primary font-medium">
                      +12% from last month
                    </p>
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardContent className="p-6">
                <div className="flex items-center">
                  <div className="p-3 green-light rounded-lg">
                    <Globe className="w-6 h-6 text-green-primary" />
                  </div>
                  <div className="ml-4">
                    <p className="text-sm font-medium text-gray-600">
                      Landfill Diverted
                    </p>
                    <p className="text-2xl font-bold text-gray-900">
                      {environmentalData.landfillDiverted} kg
                    </p>
                    <p className="text-xs text-green-primary font-medium">
                      +8% from last month
                    </p>
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardContent className="p-6">
                <div className="flex items-center">
                  <div className="p-3 green-light rounded-lg">
                    <TrendingUp className="w-6 h-6 text-green-primary" />
                  </div>
                  <div className="ml-4">
                    <p className="text-sm font-medium text-gray-600">
                      Recycling Efficiency
                    </p>
                    <p className="text-2xl font-bold text-gray-900">
                      {environmentalData.recyclingEfficiency}%
                    </p>
                    <p className="text-xs text-green-primary font-medium">
                      +5% from last month
                    </p>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {/* Environmental Goals */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center">
                  <Leaf className="w-5 h-5 mr-2 text-green-primary" />
                  Environmental Goals 2025
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-6">
                <div>
                  <div className="flex justify-between items-center mb-2">
                    <span className="text-sm font-medium">
                      Carbon Reduction Target
                    </span>
                    <span className="text-sm text-gray-600">
                      {environmentalData.carbonSaved}/500 tons
                    </span>
                  </div>
                  <Progress
                    value={calculateProgress(
                      environmentalData.carbonSaved,
                      500,
                    )}
                    className="h-2"
                  />
                  <p className="text-xs text-gray-500 mt-1">
                    {Math.round(
                      calculateProgress(environmentalData.carbonSaved, 500),
                    )}
                    % of annual target achieved
                  </p>
                </div>

                <div>
                  <div className="flex justify-between items-center mb-2">
                    <span className="text-sm font-medium">
                      Waste Diversion Target
                    </span>
                    <span className="text-sm text-gray-600">
                      {environmentalData.landfillDiverted}/2000 kg
                    </span>
                  </div>
                  <Progress
                    value={calculateProgress(
                      environmentalData.landfillDiverted,
                      2000,
                    )}
                    className="h-2"
                  />
                  <p className="text-xs text-gray-500 mt-1">
                    {Math.round(
                      calculateProgress(
                        environmentalData.landfillDiverted,
                        2000,
                      ),
                    )}
                    % of annual target achieved
                  </p>
                </div>

                <div>
                  <div className="flex justify-between items-center mb-2">
                    <span className="text-sm font-medium">
                      Recycling Efficiency Target
                    </span>
                    <span className="text-sm text-gray-600">
                      {environmentalData.recyclingEfficiency}/85%
                    </span>
                  </div>
                  <Progress
                    value={calculateProgress(
                      environmentalData.recyclingEfficiency,
                      85,
                    )}
                    className="h-2"
                  />
                  <p className="text-xs text-gray-500 mt-1">
                    {Math.round(
                      calculateProgress(
                        environmentalData.recyclingEfficiency,
                        85,
                      ),
                    )}
                    % of annual target achieved
                  </p>
                </div>
              </CardContent>
            </Card>

            {/* Monthly Trends */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center">
                  <TrendingUp className="w-5 h-5 mr-2 text-green-primary" />
                  Monthly Performance Trends
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  {environmentalData.monthlyTrends.map((month, index) => {
                    const recyclingRate = Math.round(
                      (month.recycled / month.total) * 100,
                    );
                    return (
                      <div
                        key={month.month}
                        className="p-4 bg-gray-50 rounded-lg"
                      >
                        <div className="flex justify-between items-center mb-2">
                          <span className="font-medium">
                            {month.month} 2025
                          </span>
                          <Badge className="bg-green-100 text-green-800">
                            {recyclingRate}%
                          </Badge>
                        </div>
                        <div className="grid grid-cols-2 gap-4 text-sm text-gray-600">
                          <div>
                            <span className="block">Recycled</span>
                            <span className="font-medium text-gray-900">
                              {month.recycled}kg
                            </span>
                          </div>
                          <div>
                            <span className="block">Total Waste</span>
                            <span className="font-medium text-gray-900">
                              {month.total}kg
                            </span>
                          </div>
                        </div>
                        <div className="mt-2">
                          <Progress value={recyclingRate} className="h-1" />
                        </div>
                      </div>
                    );
                  })}
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Environmental Benefits */}
          <Card className="mt-6">
            <CardHeader>
              <CardTitle className="flex items-center">
                <Factory className="w-5 h-5 mr-2 text-green-primary" />
                Environmental Benefits Achieved
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="space-y-4">
                  <h3 className="font-semibold text-gray-900">Carbon Impact</h3>
                  <div className="space-y-3">
                    <div className="flex items-center justify-between p-3 bg-green-50 rounded-lg">
                      <span className="text-sm">CO2 Emissions Reduced</span>
                      <span className="font-medium text-green-700">
                        {environmentalData.carbonSaved} tons
                      </span>
                    </div>
                    <div className="flex items-center justify-between p-3 bg-blue-50 rounded-lg">
                      <span className="text-sm">Equivalent Trees Planted</span>
                      <span className="font-medium text-blue-700">
                        {environmentalData.carbonSaved * 16} trees
                      </span>
                    </div>
                    <div className="flex items-center justify-between p-3 bg-purple-50 rounded-lg">
                      <span className="text-sm">Cars Off Road (Annual)</span>
                      <span className="font-medium text-purple-700">
                        {Math.round(environmentalData.carbonSaved * 0.5)} cars
                      </span>
                    </div>
                  </div>
                </div>

                <div className="space-y-4">
                  <h3 className="font-semibold text-gray-900">
                    Resource Conservation
                  </h3>
                  <div className="space-y-3">
                    <div className="flex items-center justify-between p-3 bg-green-50 rounded-lg">
                      <span className="text-sm">Landfill Space Saved</span>
                      <span className="font-medium text-green-700">
                        {environmentalData.landfillDiverted} kg
                      </span>
                    </div>
                    <div className="flex items-center justify-between p-3 bg-blue-50 rounded-lg">
                      <span className="text-sm">Energy Saved</span>
                      <span className="font-medium text-blue-700">
                        {Math.round(environmentalData.landfillDiverted * 2.5)}{" "}
                        kWh
                      </span>
                    </div>
                    <div className="flex items-center justify-between p-3 bg-purple-50 rounded-lg">
                      <span className="text-sm">Water Saved</span>
                      <span className="font-medium text-purple-700">
                        {Math.round(environmentalData.landfillDiverted * 15)}{" "}
                        liters
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </main>
      </div>
    </div>
  );
}
